Repository IBM/ibm-common-service-webhook, pull requests merged in 2021-11, with the labels that each got.

#66 bump version to 1.10.0
  common/scripts/next-csv.sh
  deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
  version/version.go
Labels: size/S, approved, lgtm

#68 go mod tidy for golang 1.17 for EUS
  go.mod
  go.sum
Labels: size/L, approved, lgtm

#67 go mod tidy for golang 1.17
  go.mod
Labels: size/M, approved, lgtm
