Repository IBM/ibm-common-service-webhook, pull requests merged in 2021-01, with the labels that each got.

#32 update copyright for 2021
  Makefile
  cmd/manager/main.go
  common/Makefile.common.mk
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/.githooks/pre-commit
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/push-csv.sh
  hack/boilerplate.go.txt
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/operator/group.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/podpreset_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_podpreset.go
  pkg/controller/controller.go
  pkg/controller/operandrequest/handler.go
  pkg/controller/podpreset/handler.go
  pkg/controller/podpreset/podpreset_controller.go
  pkg/utils/getEnv.go
  pkg/webhooks/operator_webhooks.go
  pkg/webhooks/reconciler.go
  pkg/webhooks/rules.go
  pkg/webhooks/webhook_register.go
  tools.go
  version/version.go
Labels: approved, lgtm, size/M

#33 added bitscuit to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#35 updated ubi image version to 8.3-230 for CS 3.6 EUS release
  Makefile
  build/Dockerfile
  deploy/olm-catalog/ibm-common-service-webhook/manifests/ibm-common-service-webhook.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#36 update cs mapping configmap
  pkg/controller/operandrequest/handler.go
Labels: approved, lgtm, size/S

#37 updated gogo/protobuf module to v1.3.2 to fix CVE-2021-3121
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#38 Porting protobuf vulnerability fix to EUS
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#39 update configmap struct
  pkg/controller/operandrequest/handler.go
Labels: approved, lgtm, size/XS
